apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph
  labels:
    app: graph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph
  template:
    metadata:
      labels:
        app: graph
    spec:
      containers:
        - image: phanikumarps/graph:alphav1
          imagePullPolicy: Always
          name: graph
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: graph
  labels:
    app: graph
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: graph
