// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID              string      `json:"id"`
	Name            *Name       `json:"name"`
	ShippingAddress *Address    `json:"shippingAddress"`
	CreditCard      *CreditCard `json:"creditCard"`
}

type Address struct {
	Country  string `json:"country"`
	Street   string `json:"street"`
	State    string `json:"state"`
	Zip      string `json:"zip"`
	Building string `json:"building"`
}

type CreditCard struct {
	Number         string `json:"number"`
	Pin            int    `json:"pin"`
	ExpirationDate string `json:"expirationDate"`
}

type Name struct {
	First string `json:"first"`
	Last  string `json:"last"`
}

type NewAccount struct {
	ID              string         `json:"id"`
	Name            *NewName       `json:"name"`
	ShippingAddress *NewAddress    `json:"shippingAddress"`
	CreditCard      *NewCreditCard `json:"creditCard"`
}

type NewAddress struct {
	Country  string `json:"country"`
	Street   string `json:"street"`
	State    string `json:"state"`
	Zip      string `json:"zip"`
	Building string `json:"building"`
}

type NewCreditCard struct {
	Number         string `json:"number"`
	Pin            int    `json:"pin"`
	ExpirationDate string `json:"expirationDate"`
}

type NewName struct {
	First string `json:"first"`
	Last  string `json:"last"`
}
